/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedCotizacionesRouteImport } from './routes/_authenticated/cotizaciones'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnosticoRouteImport } from './routes/_authenticated/diagnostico'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedMotocicletasRouteImport } from './routes/_authenticated/motocicletas'
import { Route as AuthenticatedProveedoresRouteImport } from './routes/_authenticated/proveedores'
import { Route as AuthenticatedRecepcionRouteImport } from './routes/_authenticated/recepcion'
import { Route as AuthenticatedTecnicosRouteImport } from './routes/_authenticated/tecnicos'
import { Route as AuthenticatedOrdenesIndexRouteImport } from './routes/_authenticated/ordenes.index'
import { Route as AuthenticatedOrdenesIdRouteImport } from './routes/_authenticated/ordenes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCotizacionesRoute =
  AuthenticatedCotizacionesRouteImport.update({
    id: '/cotizaciones',
    path: '/cotizaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticoRoute =
  AuthenticatedDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotocicletasRoute =
  AuthenticatedMotocicletasRouteImport.update({
    id: '/motocicletas',
    path: '/motocicletas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProveedoresRoute =
  AuthenticatedProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecepcionRoute = AuthenticatedRecepcionRouteImport.update({
  id: '/recepcion',
  path: '/recepcion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTecnicosRoute = AuthenticatedTecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdenesIndexRoute =
  AuthenticatedOrdenesIndexRouteImport.update({
    id: '/ordenes/',
    path: '/ordenes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdenesIdRoute = AuthenticatedOrdenesIdRouteImport.update({
  id: '/ordenes/$id',
  path: '/ordenes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/cotizaciones': typeof AuthenticatedCotizacionesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/motocicletas': typeof AuthenticatedMotocicletasRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/recepcion': typeof AuthenticatedRecepcionRoute
  '/tecnicos': typeof AuthenticatedTecnicosRoute
  '/ordenes/$id': typeof AuthenticatedOrdenesIdRoute
  '/ordenes/': typeof AuthenticatedOrdenesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/cotizaciones': typeof AuthenticatedCotizacionesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/motocicletas': typeof AuthenticatedMotocicletasRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/recepcion': typeof AuthenticatedRecepcionRoute
  '/tecnicos': typeof AuthenticatedTecnicosRoute
  '/ordenes/$id': typeof AuthenticatedOrdenesIdRoute
  '/ordenes': typeof AuthenticatedOrdenesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/cotizaciones': typeof AuthenticatedCotizacionesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/motocicletas': typeof AuthenticatedMotocicletasRoute
  '/_authenticated/proveedores': typeof AuthenticatedProveedoresRoute
  '/_authenticated/recepcion': typeof AuthenticatedRecepcionRoute
  '/_authenticated/tecnicos': typeof AuthenticatedTecnicosRoute
  '/_authenticated/ordenes/$id': typeof AuthenticatedOrdenesIdRoute
  '/_authenticated/ordenes/': typeof AuthenticatedOrdenesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/compras'
    | '/cotizaciones'
    | '/dashboard'
    | '/diagnostico'
    | '/inventario'
    | '/motocicletas'
    | '/proveedores'
    | '/recepcion'
    | '/tecnicos'
    | '/ordenes/$id'
    | '/ordenes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/compras'
    | '/cotizaciones'
    | '/dashboard'
    | '/diagnostico'
    | '/inventario'
    | '/motocicletas'
    | '/proveedores'
    | '/recepcion'
    | '/tecnicos'
    | '/ordenes/$id'
    | '/ordenes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/clientes'
    | '/_authenticated/compras'
    | '/_authenticated/cotizaciones'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostico'
    | '/_authenticated/inventario'
    | '/_authenticated/motocicletas'
    | '/_authenticated/proveedores'
    | '/_authenticated/recepcion'
    | '/_authenticated/tecnicos'
    | '/_authenticated/ordenes/$id'
    | '/_authenticated/ordenes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotizaciones': {
      id: '/_authenticated/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof AuthenticatedCotizacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostico': {
      id: '/_authenticated/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof AuthenticatedDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motocicletas': {
      id: '/_authenticated/motocicletas'
      path: '/motocicletas'
      fullPath: '/motocicletas'
      preLoaderRoute: typeof AuthenticatedMotocicletasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proveedores': {
      id: '/_authenticated/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof AuthenticatedProveedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recepcion': {
      id: '/_authenticated/recepcion'
      path: '/recepcion'
      fullPath: '/recepcion'
      preLoaderRoute: typeof AuthenticatedRecepcionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tecnicos': {
      id: '/_authenticated/tecnicos'
      path: '/tecnicos'
      fullPath: '/tecnicos'
      preLoaderRoute: typeof AuthenticatedTecnicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordenes/': {
      id: '/_authenticated/ordenes/'
      path: '/ordenes'
      fullPath: '/ordenes/'
      preLoaderRoute: typeof AuthenticatedOrdenesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordenes/$id': {
      id: '/_authenticated/ordenes/$id'
      path: '/ordenes/$id'
      fullPath: '/ordenes/$id'
      preLoaderRoute: typeof AuthenticatedOrdenesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedCotizacionesRoute: typeof AuthenticatedCotizacionesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticoRoute: typeof AuthenticatedDiagnosticoRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedMotocicletasRoute: typeof AuthenticatedMotocicletasRoute
  AuthenticatedProveedoresRoute: typeof AuthenticatedProveedoresRoute
  AuthenticatedRecepcionRoute: typeof AuthenticatedRecepcionRoute
  AuthenticatedTecnicosRoute: typeof AuthenticatedTecnicosRoute
  AuthenticatedOrdenesIdRoute: typeof AuthenticatedOrdenesIdRoute
  AuthenticatedOrdenesIndexRoute: typeof AuthenticatedOrdenesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedCotizacionesRoute: AuthenticatedCotizacionesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticoRoute: AuthenticatedDiagnosticoRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedMotocicletasRoute: AuthenticatedMotocicletasRoute,
  AuthenticatedProveedoresRoute: AuthenticatedProveedoresRoute,
  AuthenticatedRecepcionRoute: AuthenticatedRecepcionRoute,
  AuthenticatedTecnicosRoute: AuthenticatedTecnicosRoute,
  AuthenticatedOrdenesIdRoute: AuthenticatedOrdenesIdRoute,
  AuthenticatedOrdenesIndexRoute: AuthenticatedOrdenesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
